[workspace]
resolver="2"
members = [
    "client",
    "server",
    "shared"
]

[patch.crates-io]
naia-shared = { git = "https://github.com/Veritius/naia-changes.git", branch = "glam-and-bevy-tests" }